apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ include "argocd.ingress.name" . }}
    namespace: {{ .Values.argocd.namespace  }}
  annotations:
    {{- include "argocd.ingress.annotations" . | nindent 4 }}
spec:
  rules:
    {{- include "argocd.ingress.rules" . | nindent 4 }}