apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.deployment.name" . }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "backend.deployment.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.deployment.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.backend.containerName}}
          image: {{ .Values.backend.image.repository}}:{{ .Values.backend.image.tag}}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy}}
          resources:
            limits:
              memory: {{ .Values.backend.resources.limits.memory | quote }}
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
          {{- if .Values.backend.env }}
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.port }}
          ports:
            {{- toYaml .Values.backend.port | nindent 12 }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "backend.service.name" . }}
spec:
  selector:
    {{ include "backend.deployment.labels" . | nindent 4 }}
  type: {{ .Values.backend.service.type}}
  ports:
    - port: {{ .Values.backend.service.port}}
      targetPort: {{ .Values.backend.service.targetPort}}
      protocol: {{ .Values.backend.service.protocol}}
