apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.deployment.name" . }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      {{- include "backend.deployment.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.deployment.labels" . | nindent 6 }}
    spec:
      containers:
        - name: {{ .Values.backend.containerName}}
          image: {{ .Values.backend.image.repository}}:{{ .Values.backend.image.tag}}
          imagePullPolicy: {{ .Values.backend.image.pullPolicy}}
          resources:
            requests:
              memory: {{ .Values.backend.resources.requests.memory | quote }}
              cpu: {{ .Values.backend.resources.requests.cpu | quote }}
            limits:
              memory: {{ .Values.backend.resources.limits.memory | quote }}
              cpu: {{ .Values.backend.resources.limits.cpu | quote }}
          {{- if .Values.backend.env }}
          env:
            {{- toYaml .Values.backend.env | nindent 12 }}
          {{- end }}
          {{- if .Values.backend.port }}
          ports:
            {{- toYaml .Values.backend.port | nindent 12 }}
          {{- end }}

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
