apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ingress.name" . }}

spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- include "ingress.rules" . | nindent 4 }}