apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube.state.metrics.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kube.state.metrics.name" . }}
rules:
  {{- toYaml .Values.kubeStateMetrics.clusterRole.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube.state.metrics.name" . }}
subjects:
  {{- toYaml .Values.kubeStateMetrics.clusterRoleBinding.subjects | nindent 2 }}
roleRef:
  {{- toYaml .Values.kubeStateMetrics.clusterRoleBinding.roleRef | nindent 2 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-state-metrics
  labels:
    {{- include "kube.state.metrics.selectorLabels" . | nindent 4}}
spec:
  replicas: {{ .Values.kubeStateMetrics.deployment.replicas }}
  selector:
    matchLabels:
        {{- include "kube.state.metrics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube.state.metrics.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kube.state.metrics.name" . }}
      containers:
        - name: {{ .Values.kubeStateMetrics.deployment.containerName }}
          image: quay.io/coreos/kube-state-metrics:latest
          {{- if .Values.kubeStateMetrics.deployment.ports }}
          ports:
            {{- toYaml .Values.kubeStateMetrics.deployment.ports | nindent 12 }}
          {{- end }}  
          resources:
            {{- toYaml .Values.kubeStateMetrics.deployment.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube.state.metrics.name" . }}
spec:
  selector:
    {{- include "kube.state.metrics.selectorLabels" . | nindent 4}}
  type: {{ .Values.kubeStateMetrics.service.type }}
  ports:
    {{- toYaml .Values.kubeStateMetrics.service.ports | nindent 4 }}
