apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "network.policy.name" .}}
spec:
  podSelector:
    matchLabels:
      {{ include "mongo.deployment.selectorLabels" . | indent 6 }}
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{ include "backend.deployment.labels" . | indent 8 }}
  policyTypes:
    {{ toYaml .Values.networkPolicy.policyTypeForBackend | nindent 4}}
