apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "node.exporter.name" . }}
  namespace: {{ .Values.nodeExporter.namespace}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "node.exporter.name" . }}
rules:
  {{ toYaml .Values.nodeExporter.clusterRole.rules | nindent 2}}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "node.exporter.name" . }}
subjects:
  {{ toYaml .Values.nodeExporter.clusterRoleBinding.subjects | nindent 2}}
roleRef:
  {{ toYaml .Values.nodeExporter.clusterRoleBinding.roleRef | nindent 2}}

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "node.exporter.name" . }}
  namespace: {{ .Values.nodeExporter.namespace}}
  labels:
    {{ include "node.exporter.selectorLabels" . | nindent 4}}
spec:
  selector:
    matchLabels:
      {{ include "node.exporter.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{ include "node.exporter.selectorLabels" . | nindent 8}}
    spec:
      serviceAccountName: {{ include "node.exporter.name" . }}
      hostNetwork: {{ .Values.nodeExporter.hostNetwork}}
      containers:
        - name: prometheus-node-exporter
          image: {{ .Values.nodeExporter.image.repository}}:{{ .Values.nodeExporter.image.tag }}
          ports:
            {{ toYaml .Values.nodeExporter.ports | nindent 12 }}
          resources:
            {{ toYaml .Values.nodeExporter.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "node.exporter.name" .}}
  namespace: {{ .Values.nodeExporter.namespace }}
spec:
  selector:
    {{ include "node.exporter.selectorLabels" . | nindent 6}}
  type: {{ .Values.nodeExporter.service.type }}
  ports:
    {{ toYaml .Values.nodeExporter.service.ports | nindent 4 }}