apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.deployment.name" . }}
data:
  prometheus.yml: |
    {{ toYaml .Values.prometheus.configMap.prometheus | nindent 4 }}
  
  alert.rules.yml: |
    {{ toYaml .Values.prometheus.configMap.alertRules | nindent 4 }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "prometheus.deployment.name" . }}
spec:
  replicas: {{ .Values.prometheus.replicas }}
  selector:
    matchLabels:
      {{- include "prometheus.deployment.selectorLabel" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "prometheus.deployment.selectorLabel" . | nindent 8}}
    spec:
      containers:
        - name: {{ .Values.prometheus.containerName}}
          image: {{ .Values.prometheus.image.repository}}:{{ .Values.prometheus.image.tag}}
          args:
            {{ toYaml .Values.prometheus.args | nindent 12 }}
          ports:
            {{ toYaml .Values.prometheus.ports | nindent 12}}
          resources:
            {{ toYaml .Values.prometheus.resources | nindent 12}}
          volumeMounts:
            - name: {{ .Values.prometheus.volumes.prometheusConfigName }}
              mountPath: {{ .Values.prometheus.volumes.mountPath }}
      volumes:
        - name: {{ .Values.prometheus.volumes.prometheusConfigName }}
          configMap:
            name: {{ include "prometheus.deployment.name" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "prometheus.deployment.name" . }}
spec:
  selector:
    {{ include "prometheus.deployment.selectorLabel" . | nindent 4}}
  ports:
    {{ toYaml .Values.prometheus.service.ports | nindent 4}}
  type: {{ .Values.prometheus.service.type }}
