apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: {{ include "secret.store.name" . }}
spec:
  provider:
    {{- toYaml .Values.secretStore.provider | nindent 4 }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "external.secret.name" . }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval}}
  secretStoreRef:
    name: {{ include "secret.store.name" . }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ include "external.secret.secret.name" . }}
  data:
    {{- toYaml .Values.externalSecret.data | nindent 4 }}
