apiVersion: batch/v1
kind: Job
metadata:
  {{- include "stress.job.name" . | nindent 2 }}
spec:
  completions: {{ .Values.stressJob.completions }}
  template:
    metadata:
      {{- include "stress.job.name" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.stressJob.containerName }}
          image: {{ .Values.stressJob.image.repository}}:{{ .Values.stressJob.image.tag }}
          imagePullPolicy: {{ .Values.stressJob.image.pullPolicy}}
          command: {{ .Values.stressJob.command }}
      restartPolicy: {{ .Values.stressJob.restartPolicy }}